server:
  port: 8081

spring:
  application:
    name: 'provider'
  datasource:
    password: 'admin'
    username: 'root'
    url: 'jdbc:mysql://localhost:3306/provider'
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone : http://localhost:8761/eureka